# Makefile.in generated by automake 1.16.2 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2020 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/antfx
pkgincludedir = $(includedir)/antfx
pkglibdir = $(libdir)/antfx
pkglibexecdir = $(libexecdir)/antfx
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = arm-poky-linux-gnu
bin_PROGRAMS = antfx$(EXEEXT)
#am__append_1 = backends/sdl2_engine.c
am__append_2 = backends/fb_engine.c
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__antfx_SOURCES_DIST = antfxapp.c antfx.c backends/sdl2_engine.c \
	backends/fb_engine.c lib/liblv/lv_core/lv_group.c \
	lib/liblv/lv_core/lv_indev.c lib/liblv/lv_core/lv_disp.c \
	lib/liblv/lv_core/lv_obj.c lib/liblv/lv_core/lv_refr.c \
	lib/liblv/lv_core/lv_style.c lib/liblv/lv_core/lv_debug.c \
	lib/liblv/lv_draw/lv_draw_basic.c lib/liblv/lv_draw/lv_draw.c \
	lib/liblv/lv_draw/lv_draw_rect.c \
	lib/liblv/lv_draw/lv_draw_label.c \
	lib/liblv/lv_draw/lv_draw_line.c \
	lib/liblv/lv_draw/lv_draw_img.c \
	lib/liblv/lv_draw/lv_draw_arc.c \
	lib/liblv/lv_draw/lv_draw_triangle.c \
	lib/liblv/lv_draw/lv_img_decoder.c \
	lib/liblv/lv_draw/lv_img_cache.c lib/liblv/lv_font/lv_font.c \
	lib/liblv/lv_font/lv_font_fmt_txt.c \
	lib/liblv/lv_font/lv_font_roboto_12.c \
	lib/liblv/lv_font/lv_font_roboto_16.c \
	lib/liblv/lv_font/lv_font_roboto_22.c \
	lib/liblv/lv_font/lv_font_roboto_28.c \
	lib/liblv/lv_font/lv_font_unscii_8.c \
	lib/liblv/lv_hal/lv_hal_disp.c lib/liblv/lv_hal/lv_hal_indev.c \
	lib/liblv/lv_hal/lv_hal_tick.c lib/liblv/lv_misc/lv_circ.c \
	lib/liblv/lv_misc/lv_area.c lib/liblv/lv_misc/lv_task.c \
	lib/liblv/lv_misc/lv_fs.c lib/liblv/lv_misc/lv_anim.c \
	lib/liblv/lv_misc/lv_mem.c lib/liblv/lv_misc/lv_ll.c \
	lib/liblv/lv_misc/lv_color.c lib/liblv/lv_misc/lv_txt.c \
	lib/liblv/lv_misc/lv_math.c lib/liblv/lv_misc/lv_log.c \
	lib/liblv/lv_misc/lv_gc.c lib/liblv/lv_misc/lv_utils.c \
	lib/liblv/lv_misc/lv_async.c lib/liblv/lv_misc/lv_printf.c \
	lib/liblv/lv_misc/lv_bidi.c lib/liblv/lv_objx/lv_arc.c \
	lib/liblv/lv_objx/lv_bar.c lib/liblv/lv_objx/lv_cb.c \
	lib/liblv/lv_objx/lv_cpicker.c lib/liblv/lv_objx/lv_ddlist.c \
	lib/liblv/lv_objx/lv_kb.c lib/liblv/lv_objx/lv_line.c \
	lib/liblv/lv_objx/lv_mbox.c lib/liblv/lv_objx/lv_preload.c \
	lib/liblv/lv_objx/lv_roller.c lib/liblv/lv_objx/lv_table.c \
	lib/liblv/lv_objx/lv_tabview.c lib/liblv/lv_objx/lv_tileview.c \
	lib/liblv/lv_objx/lv_btn.c lib/liblv/lv_objx/lv_calendar.c \
	lib/liblv/lv_objx/lv_chart.c lib/liblv/lv_objx/lv_canvas.c \
	lib/liblv/lv_objx/lv_gauge.c lib/liblv/lv_objx/lv_label.c \
	lib/liblv/lv_objx/lv_list.c lib/liblv/lv_objx/lv_slider.c \
	lib/liblv/lv_objx/lv_ta.c lib/liblv/lv_objx/lv_spinbox.c \
	lib/liblv/lv_objx/lv_btnm.c lib/liblv/lv_objx/lv_cont.c \
	lib/liblv/lv_objx/lv_img.c lib/liblv/lv_objx/lv_imgbtn.c \
	lib/liblv/lv_objx/lv_led.c lib/liblv/lv_objx/lv_lmeter.c \
	lib/liblv/lv_objx/lv_page.c lib/liblv/lv_objx/lv_sw.c \
	lib/liblv/lv_objx/lv_win.c \
	lib/liblv/lv_themes/lv_theme_alien.c \
	lib/liblv/lv_themes/lv_theme.c \
	lib/liblv/lv_themes/lv_theme_default.c \
	lib/liblv/lv_themes/lv_theme_night.c \
	lib/liblv/lv_themes/lv_theme_templ.c \
	lib/liblv/lv_themes/lv_theme_zen.c \
	lib/liblv/lv_themes/lv_theme_material.c \
	lib/liblv/lv_themes/lv_theme_nemo.c \
	lib/liblv/lv_themes/lv_theme_mono.c
am__dirstamp = $(am__leading_dot)dirstamp
#am__objects_1 = backends/sdl2_engine.$(OBJEXT)
am__objects_2 = backends/fb_engine.$(OBJEXT)
am_antfx_OBJECTS = antfxapp.$(OBJEXT) antfx.$(OBJEXT) $(am__objects_1) \
	$(am__objects_2) lib/liblv/lv_core/lv_group.$(OBJEXT) \
	lib/liblv/lv_core/lv_indev.$(OBJEXT) \
	lib/liblv/lv_core/lv_disp.$(OBJEXT) \
	lib/liblv/lv_core/lv_obj.$(OBJEXT) \
	lib/liblv/lv_core/lv_refr.$(OBJEXT) \
	lib/liblv/lv_core/lv_style.$(OBJEXT) \
	lib/liblv/lv_core/lv_debug.$(OBJEXT) \
	lib/liblv/lv_draw/lv_draw_basic.$(OBJEXT) \
	lib/liblv/lv_draw/lv_draw.$(OBJEXT) \
	lib/liblv/lv_draw/lv_draw_rect.$(OBJEXT) \
	lib/liblv/lv_draw/lv_draw_label.$(OBJEXT) \
	lib/liblv/lv_draw/lv_draw_line.$(OBJEXT) \
	lib/liblv/lv_draw/lv_draw_img.$(OBJEXT) \
	lib/liblv/lv_draw/lv_draw_arc.$(OBJEXT) \
	lib/liblv/lv_draw/lv_draw_triangle.$(OBJEXT) \
	lib/liblv/lv_draw/lv_img_decoder.$(OBJEXT) \
	lib/liblv/lv_draw/lv_img_cache.$(OBJEXT) \
	lib/liblv/lv_font/lv_font.$(OBJEXT) \
	lib/liblv/lv_font/lv_font_fmt_txt.$(OBJEXT) \
	lib/liblv/lv_font/lv_font_roboto_12.$(OBJEXT) \
	lib/liblv/lv_font/lv_font_roboto_16.$(OBJEXT) \
	lib/liblv/lv_font/lv_font_roboto_22.$(OBJEXT) \
	lib/liblv/lv_font/lv_font_roboto_28.$(OBJEXT) \
	lib/liblv/lv_font/lv_font_unscii_8.$(OBJEXT) \
	lib/liblv/lv_hal/lv_hal_disp.$(OBJEXT) \
	lib/liblv/lv_hal/lv_hal_indev.$(OBJEXT) \
	lib/liblv/lv_hal/lv_hal_tick.$(OBJEXT) \
	lib/liblv/lv_misc/lv_circ.$(OBJEXT) \
	lib/liblv/lv_misc/lv_area.$(OBJEXT) \
	lib/liblv/lv_misc/lv_task.$(OBJEXT) \
	lib/liblv/lv_misc/lv_fs.$(OBJEXT) \
	lib/liblv/lv_misc/lv_anim.$(OBJEXT) \
	lib/liblv/lv_misc/lv_mem.$(OBJEXT) \
	lib/liblv/lv_misc/lv_ll.$(OBJEXT) \
	lib/liblv/lv_misc/lv_color.$(OBJEXT) \
	lib/liblv/lv_misc/lv_txt.$(OBJEXT) \
	lib/liblv/lv_misc/lv_math.$(OBJEXT) \
	lib/liblv/lv_misc/lv_log.$(OBJEXT) \
	lib/liblv/lv_misc/lv_gc.$(OBJEXT) \
	lib/liblv/lv_misc/lv_utils.$(OBJEXT) \
	lib/liblv/lv_misc/lv_async.$(OBJEXT) \
	lib/liblv/lv_misc/lv_printf.$(OBJEXT) \
	lib/liblv/lv_misc/lv_bidi.$(OBJEXT) \
	lib/liblv/lv_objx/lv_arc.$(OBJEXT) \
	lib/liblv/lv_objx/lv_bar.$(OBJEXT) \
	lib/liblv/lv_objx/lv_cb.$(OBJEXT) \
	lib/liblv/lv_objx/lv_cpicker.$(OBJEXT) \
	lib/liblv/lv_objx/lv_ddlist.$(OBJEXT) \
	lib/liblv/lv_objx/lv_kb.$(OBJEXT) \
	lib/liblv/lv_objx/lv_line.$(OBJEXT) \
	lib/liblv/lv_objx/lv_mbox.$(OBJEXT) \
	lib/liblv/lv_objx/lv_preload.$(OBJEXT) \
	lib/liblv/lv_objx/lv_roller.$(OBJEXT) \
	lib/liblv/lv_objx/lv_table.$(OBJEXT) \
	lib/liblv/lv_objx/lv_tabview.$(OBJEXT) \
	lib/liblv/lv_objx/lv_tileview.$(OBJEXT) \
	lib/liblv/lv_objx/lv_btn.$(OBJEXT) \
	lib/liblv/lv_objx/lv_calendar.$(OBJEXT) \
	lib/liblv/lv_objx/lv_chart.$(OBJEXT) \
	lib/liblv/lv_objx/lv_canvas.$(OBJEXT) \
	lib/liblv/lv_objx/lv_gauge.$(OBJEXT) \
	lib/liblv/lv_objx/lv_label.$(OBJEXT) \
	lib/liblv/lv_objx/lv_list.$(OBJEXT) \
	lib/liblv/lv_objx/lv_slider.$(OBJEXT) \
	lib/liblv/lv_objx/lv_ta.$(OBJEXT) \
	lib/liblv/lv_objx/lv_spinbox.$(OBJEXT) \
	lib/liblv/lv_objx/lv_btnm.$(OBJEXT) \
	lib/liblv/lv_objx/lv_cont.$(OBJEXT) \
	lib/liblv/lv_objx/lv_img.$(OBJEXT) \
	lib/liblv/lv_objx/lv_imgbtn.$(OBJEXT) \
	lib/liblv/lv_objx/lv_led.$(OBJEXT) \
	lib/liblv/lv_objx/lv_lmeter.$(OBJEXT) \
	lib/liblv/lv_objx/lv_page.$(OBJEXT) \
	lib/liblv/lv_objx/lv_sw.$(OBJEXT) \
	lib/liblv/lv_objx/lv_win.$(OBJEXT) \
	lib/liblv/lv_themes/lv_theme_alien.$(OBJEXT) \
	lib/liblv/lv_themes/lv_theme.$(OBJEXT) \
	lib/liblv/lv_themes/lv_theme_default.$(OBJEXT) \
	lib/liblv/lv_themes/lv_theme_night.$(OBJEXT) \
	lib/liblv/lv_themes/lv_theme_templ.$(OBJEXT) \
	lib/liblv/lv_themes/lv_theme_zen.$(OBJEXT) \
	lib/liblv/lv_themes/lv_theme_material.$(OBJEXT) \
	lib/liblv/lv_themes/lv_theme_nemo.$(OBJEXT) \
	lib/liblv/lv_themes/lv_theme_mono.$(OBJEXT)
antfx_OBJECTS = $(am_antfx_OBJECTS)
antfx_LDADD = $(LDADD)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/antfx.Po ./$(DEPDIR)/antfxapp.Po \
	backends/$(DEPDIR)/fb_engine.Po \
	backends/$(DEPDIR)/sdl2_engine.Po \
	lib/liblv/lv_core/$(DEPDIR)/lv_debug.Po \
	lib/liblv/lv_core/$(DEPDIR)/lv_disp.Po \
	lib/liblv/lv_core/$(DEPDIR)/lv_group.Po \
	lib/liblv/lv_core/$(DEPDIR)/lv_indev.Po \
	lib/liblv/lv_core/$(DEPDIR)/lv_obj.Po \
	lib/liblv/lv_core/$(DEPDIR)/lv_refr.Po \
	lib/liblv/lv_core/$(DEPDIR)/lv_style.Po \
	lib/liblv/lv_draw/$(DEPDIR)/lv_draw.Po \
	lib/liblv/lv_draw/$(DEPDIR)/lv_draw_arc.Po \
	lib/liblv/lv_draw/$(DEPDIR)/lv_draw_basic.Po \
	lib/liblv/lv_draw/$(DEPDIR)/lv_draw_img.Po \
	lib/liblv/lv_draw/$(DEPDIR)/lv_draw_label.Po \
	lib/liblv/lv_draw/$(DEPDIR)/lv_draw_line.Po \
	lib/liblv/lv_draw/$(DEPDIR)/lv_draw_rect.Po \
	lib/liblv/lv_draw/$(DEPDIR)/lv_draw_triangle.Po \
	lib/liblv/lv_draw/$(DEPDIR)/lv_img_cache.Po \
	lib/liblv/lv_draw/$(DEPDIR)/lv_img_decoder.Po \
	lib/liblv/lv_font/$(DEPDIR)/lv_font.Po \
	lib/liblv/lv_font/$(DEPDIR)/lv_font_fmt_txt.Po \
	lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_12.Po \
	lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_16.Po \
	lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_22.Po \
	lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_28.Po \
	lib/liblv/lv_font/$(DEPDIR)/lv_font_unscii_8.Po \
	lib/liblv/lv_hal/$(DEPDIR)/lv_hal_disp.Po \
	lib/liblv/lv_hal/$(DEPDIR)/lv_hal_indev.Po \
	lib/liblv/lv_hal/$(DEPDIR)/lv_hal_tick.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_anim.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_area.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_async.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_bidi.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_circ.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_color.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_fs.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_gc.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_ll.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_log.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_math.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_mem.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_printf.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_task.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_txt.Po \
	lib/liblv/lv_misc/$(DEPDIR)/lv_utils.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_arc.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_bar.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_btn.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_btnm.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_calendar.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_canvas.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_cb.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_chart.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_cont.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_cpicker.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_ddlist.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_gauge.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_img.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_imgbtn.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_kb.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_label.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_led.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_line.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_list.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_lmeter.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_mbox.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_page.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_preload.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_roller.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_slider.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_spinbox.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_sw.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_ta.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_table.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_tabview.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_tileview.Po \
	lib/liblv/lv_objx/$(DEPDIR)/lv_win.Po \
	lib/liblv/lv_themes/$(DEPDIR)/lv_theme.Po \
	lib/liblv/lv_themes/$(DEPDIR)/lv_theme_alien.Po \
	lib/liblv/lv_themes/$(DEPDIR)/lv_theme_default.Po \
	lib/liblv/lv_themes/$(DEPDIR)/lv_theme_material.Po \
	lib/liblv/lv_themes/$(DEPDIR)/lv_theme_mono.Po \
	lib/liblv/lv_themes/$(DEPDIR)/lv_theme_nemo.Po \
	lib/liblv/lv_themes/$(DEPDIR)/lv_theme_night.Po \
	lib/liblv/lv_themes/$(DEPDIR)/lv_theme_templ.Po \
	lib/liblv/lv_themes/$(DEPDIR)/lv_theme_zen.Po
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(antfx_SOURCES)
DIST_SOURCES = $(am__antfx_SOURCES_DIST)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in compile config.guess \
	config.sub depcomp install-sh ltmain.sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/mrsang/workspace/antfx/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = ${SHELL} /home/mrsang/workspace/antfx/missing autoconf
AUTOHEADER = ${SHELL} /home/mrsang/workspace/antfx/missing autoheader
AUTOMAKE = ${SHELL} /home/mrsang/workspace/antfx/missing automake-1.16
AWK = gawk
CC = arm-poky-linux-gnueabi-gcc  -march=armv6 -mfpu=vfp -mfloat-abi=hard -mtune=arm1176jzf-s -mfpu=vfp -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/media/games/mrsang/rpi-toolchain/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi
CCDEPMODE = depmode=gcc3
CFLAGS =  -O2 -pipe -g -feliminate-unused-debug-types 
CPP = arm-poky-linux-gnueabi-gcc -E  -march=armv6 -mfpu=vfp -mfloat-abi=hard -mtune=arm1176jzf-s -mfpu=vfp -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/media/games/mrsang/rpi-toolchain/sysroots/arm1176jzfshf-vfp-poky-linux-gnueabi
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"antfx\" -DPACKAGE_TARNAME=\"antfx\" -DPACKAGE_VERSION=\"1.0.0b\" -DPACKAGE_STRING=\"antfx\ 1.0.0b\" -DPACKAGE_BUGREPORT=\"xsang.le@gmail.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"antfx\" -DVERSION=\"1.0.0b\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIBTS=1 -D_GNU_SOURCE=1 -DLINUX=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now
LIBOBJS = 
LIBS = -lts 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/mrsang/workspace/antfx/missing makeinfo
MKDIR_P = /usr/bin/mkdir -p
OBJEXT = o
PACKAGE = antfx
PACKAGE_BUGREPORT = xsang.le@gmail.com
PACKAGE_NAME = antfx
PACKAGE_STRING = antfx 1.0.0b
PACKAGE_TARNAME = antfx
PACKAGE_URL = 
PACKAGE_VERSION = 1.0.0b
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/bash
STRIP = arm-poky-linux-gnueabi-strip
VERSION = 1.0.0b
abs_builddir = /home/mrsang/workspace/antfx
abs_srcdir = /home/mrsang/workspace/antfx
abs_top_builddir = /home/mrsang/workspace/antfx
abs_top_srcdir = /home/mrsang/workspace/antfx
ac_ct_CC = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = arm-poky-linux-gnu
host_alias = arm-poky-linux
host_cpu = arm
host_os = linux-gnu
host_vendor = poky
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/mrsang/workspace/antfx/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = arm-poky-linux
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = foreign
AM_CPPFLAGS = -W  -Wall -g -std=c99

# SUBDIRS =  lib/ .
EXTRA_DIST = README.md
# lib source files
antfx_SOURCES = antfxapp.c antfx.c $(am__append_1) $(am__append_2) \
	lib/liblv/lv_core/lv_group.c lib/liblv/lv_core/lv_indev.c \
	lib/liblv/lv_core/lv_disp.c lib/liblv/lv_core/lv_obj.c \
	lib/liblv/lv_core/lv_refr.c lib/liblv/lv_core/lv_style.c \
	lib/liblv/lv_core/lv_debug.c lib/liblv/lv_draw/lv_draw_basic.c \
	lib/liblv/lv_draw/lv_draw.c lib/liblv/lv_draw/lv_draw_rect.c \
	lib/liblv/lv_draw/lv_draw_label.c \
	lib/liblv/lv_draw/lv_draw_line.c \
	lib/liblv/lv_draw/lv_draw_img.c \
	lib/liblv/lv_draw/lv_draw_arc.c \
	lib/liblv/lv_draw/lv_draw_triangle.c \
	lib/liblv/lv_draw/lv_img_decoder.c \
	lib/liblv/lv_draw/lv_img_cache.c lib/liblv/lv_font/lv_font.c \
	lib/liblv/lv_font/lv_font_fmt_txt.c \
	lib/liblv/lv_font/lv_font_roboto_12.c \
	lib/liblv/lv_font/lv_font_roboto_16.c \
	lib/liblv/lv_font/lv_font_roboto_22.c \
	lib/liblv/lv_font/lv_font_roboto_28.c \
	lib/liblv/lv_font/lv_font_unscii_8.c \
	lib/liblv/lv_hal/lv_hal_disp.c lib/liblv/lv_hal/lv_hal_indev.c \
	lib/liblv/lv_hal/lv_hal_tick.c lib/liblv/lv_misc/lv_circ.c \
	lib/liblv/lv_misc/lv_area.c lib/liblv/lv_misc/lv_task.c \
	lib/liblv/lv_misc/lv_fs.c lib/liblv/lv_misc/lv_anim.c \
	lib/liblv/lv_misc/lv_mem.c lib/liblv/lv_misc/lv_ll.c \
	lib/liblv/lv_misc/lv_color.c lib/liblv/lv_misc/lv_txt.c \
	lib/liblv/lv_misc/lv_math.c lib/liblv/lv_misc/lv_log.c \
	lib/liblv/lv_misc/lv_gc.c lib/liblv/lv_misc/lv_utils.c \
	lib/liblv/lv_misc/lv_async.c lib/liblv/lv_misc/lv_printf.c \
	lib/liblv/lv_misc/lv_bidi.c lib/liblv/lv_objx/lv_arc.c \
	lib/liblv/lv_objx/lv_bar.c lib/liblv/lv_objx/lv_cb.c \
	lib/liblv/lv_objx/lv_cpicker.c lib/liblv/lv_objx/lv_ddlist.c \
	lib/liblv/lv_objx/lv_kb.c lib/liblv/lv_objx/lv_line.c \
	lib/liblv/lv_objx/lv_mbox.c lib/liblv/lv_objx/lv_preload.c \
	lib/liblv/lv_objx/lv_roller.c lib/liblv/lv_objx/lv_table.c \
	lib/liblv/lv_objx/lv_tabview.c lib/liblv/lv_objx/lv_tileview.c \
	lib/liblv/lv_objx/lv_btn.c lib/liblv/lv_objx/lv_calendar.c \
	lib/liblv/lv_objx/lv_chart.c lib/liblv/lv_objx/lv_canvas.c \
	lib/liblv/lv_objx/lv_gauge.c lib/liblv/lv_objx/lv_label.c \
	lib/liblv/lv_objx/lv_list.c lib/liblv/lv_objx/lv_slider.c \
	lib/liblv/lv_objx/lv_ta.c lib/liblv/lv_objx/lv_spinbox.c \
	lib/liblv/lv_objx/lv_btnm.c lib/liblv/lv_objx/lv_cont.c \
	lib/liblv/lv_objx/lv_img.c lib/liblv/lv_objx/lv_imgbtn.c \
	lib/liblv/lv_objx/lv_led.c lib/liblv/lv_objx/lv_lmeter.c \
	lib/liblv/lv_objx/lv_page.c lib/liblv/lv_objx/lv_sw.c \
	lib/liblv/lv_objx/lv_win.c \
	lib/liblv/lv_themes/lv_theme_alien.c \
	lib/liblv/lv_themes/lv_theme.c \
	lib/liblv/lv_themes/lv_theme_default.c \
	lib/liblv/lv_themes/lv_theme_night.c \
	lib/liblv/lv_themes/lv_theme_templ.c \
	lib/liblv/lv_themes/lv_theme_zen.c \
	lib/liblv/lv_themes/lv_theme_material.c \
	lib/liblv/lv_themes/lv_theme_nemo.c \
	lib/liblv/lv_themes/lv_theme_mono.c
all: all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
backends/$(am__dirstamp):
	@$(MKDIR_P) backends
	@: > backends/$(am__dirstamp)
backends/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) backends/$(DEPDIR)
	@: > backends/$(DEPDIR)/$(am__dirstamp)
backends/sdl2_engine.$(OBJEXT): backends/$(am__dirstamp) \
	backends/$(DEPDIR)/$(am__dirstamp)
backends/fb_engine.$(OBJEXT): backends/$(am__dirstamp) \
	backends/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_core/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_core
	@: > lib/liblv/lv_core/$(am__dirstamp)
lib/liblv/lv_core/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_core/$(DEPDIR)
	@: > lib/liblv/lv_core/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_core/lv_group.$(OBJEXT):  \
	lib/liblv/lv_core/$(am__dirstamp) \
	lib/liblv/lv_core/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_core/lv_indev.$(OBJEXT):  \
	lib/liblv/lv_core/$(am__dirstamp) \
	lib/liblv/lv_core/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_core/lv_disp.$(OBJEXT):  \
	lib/liblv/lv_core/$(am__dirstamp) \
	lib/liblv/lv_core/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_core/lv_obj.$(OBJEXT): lib/liblv/lv_core/$(am__dirstamp) \
	lib/liblv/lv_core/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_core/lv_refr.$(OBJEXT):  \
	lib/liblv/lv_core/$(am__dirstamp) \
	lib/liblv/lv_core/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_core/lv_style.$(OBJEXT):  \
	lib/liblv/lv_core/$(am__dirstamp) \
	lib/liblv/lv_core/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_core/lv_debug.$(OBJEXT):  \
	lib/liblv/lv_core/$(am__dirstamp) \
	lib/liblv/lv_core/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_draw
	@: > lib/liblv/lv_draw/$(am__dirstamp)
lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_draw/$(DEPDIR)
	@: > lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/lv_draw_basic.$(OBJEXT):  \
	lib/liblv/lv_draw/$(am__dirstamp) \
	lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/lv_draw.$(OBJEXT):  \
	lib/liblv/lv_draw/$(am__dirstamp) \
	lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/lv_draw_rect.$(OBJEXT):  \
	lib/liblv/lv_draw/$(am__dirstamp) \
	lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/lv_draw_label.$(OBJEXT):  \
	lib/liblv/lv_draw/$(am__dirstamp) \
	lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/lv_draw_line.$(OBJEXT):  \
	lib/liblv/lv_draw/$(am__dirstamp) \
	lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/lv_draw_img.$(OBJEXT):  \
	lib/liblv/lv_draw/$(am__dirstamp) \
	lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/lv_draw_arc.$(OBJEXT):  \
	lib/liblv/lv_draw/$(am__dirstamp) \
	lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/lv_draw_triangle.$(OBJEXT):  \
	lib/liblv/lv_draw/$(am__dirstamp) \
	lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/lv_img_decoder.$(OBJEXT):  \
	lib/liblv/lv_draw/$(am__dirstamp) \
	lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_draw/lv_img_cache.$(OBJEXT):  \
	lib/liblv/lv_draw/$(am__dirstamp) \
	lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_font/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_font
	@: > lib/liblv/lv_font/$(am__dirstamp)
lib/liblv/lv_font/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_font/$(DEPDIR)
	@: > lib/liblv/lv_font/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_font/lv_font.$(OBJEXT):  \
	lib/liblv/lv_font/$(am__dirstamp) \
	lib/liblv/lv_font/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_font/lv_font_fmt_txt.$(OBJEXT):  \
	lib/liblv/lv_font/$(am__dirstamp) \
	lib/liblv/lv_font/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_font/lv_font_roboto_12.$(OBJEXT):  \
	lib/liblv/lv_font/$(am__dirstamp) \
	lib/liblv/lv_font/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_font/lv_font_roboto_16.$(OBJEXT):  \
	lib/liblv/lv_font/$(am__dirstamp) \
	lib/liblv/lv_font/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_font/lv_font_roboto_22.$(OBJEXT):  \
	lib/liblv/lv_font/$(am__dirstamp) \
	lib/liblv/lv_font/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_font/lv_font_roboto_28.$(OBJEXT):  \
	lib/liblv/lv_font/$(am__dirstamp) \
	lib/liblv/lv_font/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_font/lv_font_unscii_8.$(OBJEXT):  \
	lib/liblv/lv_font/$(am__dirstamp) \
	lib/liblv/lv_font/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_hal/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_hal
	@: > lib/liblv/lv_hal/$(am__dirstamp)
lib/liblv/lv_hal/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_hal/$(DEPDIR)
	@: > lib/liblv/lv_hal/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_hal/lv_hal_disp.$(OBJEXT):  \
	lib/liblv/lv_hal/$(am__dirstamp) \
	lib/liblv/lv_hal/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_hal/lv_hal_indev.$(OBJEXT):  \
	lib/liblv/lv_hal/$(am__dirstamp) \
	lib/liblv/lv_hal/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_hal/lv_hal_tick.$(OBJEXT):  \
	lib/liblv/lv_hal/$(am__dirstamp) \
	lib/liblv/lv_hal/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_misc
	@: > lib/liblv/lv_misc/$(am__dirstamp)
lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_misc/$(DEPDIR)
	@: > lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_circ.$(OBJEXT):  \
	lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_area.$(OBJEXT):  \
	lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_task.$(OBJEXT):  \
	lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_fs.$(OBJEXT): lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_anim.$(OBJEXT):  \
	lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_mem.$(OBJEXT): lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_ll.$(OBJEXT): lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_color.$(OBJEXT):  \
	lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_txt.$(OBJEXT): lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_math.$(OBJEXT):  \
	lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_log.$(OBJEXT): lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_gc.$(OBJEXT): lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_utils.$(OBJEXT):  \
	lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_async.$(OBJEXT):  \
	lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_printf.$(OBJEXT):  \
	lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_misc/lv_bidi.$(OBJEXT):  \
	lib/liblv/lv_misc/$(am__dirstamp) \
	lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_objx
	@: > lib/liblv/lv_objx/$(am__dirstamp)
lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_objx/$(DEPDIR)
	@: > lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_arc.$(OBJEXT): lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_bar.$(OBJEXT): lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_cb.$(OBJEXT): lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_cpicker.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_ddlist.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_kb.$(OBJEXT): lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_line.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_mbox.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_preload.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_roller.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_table.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_tabview.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_tileview.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_btn.$(OBJEXT): lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_calendar.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_chart.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_canvas.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_gauge.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_label.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_list.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_slider.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_ta.$(OBJEXT): lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_spinbox.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_btnm.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_cont.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_img.$(OBJEXT): lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_imgbtn.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_led.$(OBJEXT): lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_lmeter.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_page.$(OBJEXT):  \
	lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_sw.$(OBJEXT): lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_objx/lv_win.$(OBJEXT): lib/liblv/lv_objx/$(am__dirstamp) \
	lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_themes/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_themes
	@: > lib/liblv/lv_themes/$(am__dirstamp)
lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) lib/liblv/lv_themes/$(DEPDIR)
	@: > lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_themes/lv_theme_alien.$(OBJEXT):  \
	lib/liblv/lv_themes/$(am__dirstamp) \
	lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_themes/lv_theme.$(OBJEXT):  \
	lib/liblv/lv_themes/$(am__dirstamp) \
	lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_themes/lv_theme_default.$(OBJEXT):  \
	lib/liblv/lv_themes/$(am__dirstamp) \
	lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_themes/lv_theme_night.$(OBJEXT):  \
	lib/liblv/lv_themes/$(am__dirstamp) \
	lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_themes/lv_theme_templ.$(OBJEXT):  \
	lib/liblv/lv_themes/$(am__dirstamp) \
	lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_themes/lv_theme_zen.$(OBJEXT):  \
	lib/liblv/lv_themes/$(am__dirstamp) \
	lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_themes/lv_theme_material.$(OBJEXT):  \
	lib/liblv/lv_themes/$(am__dirstamp) \
	lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_themes/lv_theme_nemo.$(OBJEXT):  \
	lib/liblv/lv_themes/$(am__dirstamp) \
	lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)
lib/liblv/lv_themes/lv_theme_mono.$(OBJEXT):  \
	lib/liblv/lv_themes/$(am__dirstamp) \
	lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)

antfx$(EXEEXT): $(antfx_OBJECTS) $(antfx_DEPENDENCIES) $(EXTRA_antfx_DEPENDENCIES) 
	@rm -f antfx$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(antfx_OBJECTS) $(antfx_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f backends/*.$(OBJEXT)
	-rm -f lib/liblv/lv_core/*.$(OBJEXT)
	-rm -f lib/liblv/lv_draw/*.$(OBJEXT)
	-rm -f lib/liblv/lv_font/*.$(OBJEXT)
	-rm -f lib/liblv/lv_hal/*.$(OBJEXT)
	-rm -f lib/liblv/lv_misc/*.$(OBJEXT)
	-rm -f lib/liblv/lv_objx/*.$(OBJEXT)
	-rm -f lib/liblv/lv_themes/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/antfx.Po # am--include-marker
include ./$(DEPDIR)/antfxapp.Po # am--include-marker
include backends/$(DEPDIR)/fb_engine.Po # am--include-marker
include backends/$(DEPDIR)/sdl2_engine.Po # am--include-marker
include lib/liblv/lv_core/$(DEPDIR)/lv_debug.Po # am--include-marker
include lib/liblv/lv_core/$(DEPDIR)/lv_disp.Po # am--include-marker
include lib/liblv/lv_core/$(DEPDIR)/lv_group.Po # am--include-marker
include lib/liblv/lv_core/$(DEPDIR)/lv_indev.Po # am--include-marker
include lib/liblv/lv_core/$(DEPDIR)/lv_obj.Po # am--include-marker
include lib/liblv/lv_core/$(DEPDIR)/lv_refr.Po # am--include-marker
include lib/liblv/lv_core/$(DEPDIR)/lv_style.Po # am--include-marker
include lib/liblv/lv_draw/$(DEPDIR)/lv_draw.Po # am--include-marker
include lib/liblv/lv_draw/$(DEPDIR)/lv_draw_arc.Po # am--include-marker
include lib/liblv/lv_draw/$(DEPDIR)/lv_draw_basic.Po # am--include-marker
include lib/liblv/lv_draw/$(DEPDIR)/lv_draw_img.Po # am--include-marker
include lib/liblv/lv_draw/$(DEPDIR)/lv_draw_label.Po # am--include-marker
include lib/liblv/lv_draw/$(DEPDIR)/lv_draw_line.Po # am--include-marker
include lib/liblv/lv_draw/$(DEPDIR)/lv_draw_rect.Po # am--include-marker
include lib/liblv/lv_draw/$(DEPDIR)/lv_draw_triangle.Po # am--include-marker
include lib/liblv/lv_draw/$(DEPDIR)/lv_img_cache.Po # am--include-marker
include lib/liblv/lv_draw/$(DEPDIR)/lv_img_decoder.Po # am--include-marker
include lib/liblv/lv_font/$(DEPDIR)/lv_font.Po # am--include-marker
include lib/liblv/lv_font/$(DEPDIR)/lv_font_fmt_txt.Po # am--include-marker
include lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_12.Po # am--include-marker
include lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_16.Po # am--include-marker
include lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_22.Po # am--include-marker
include lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_28.Po # am--include-marker
include lib/liblv/lv_font/$(DEPDIR)/lv_font_unscii_8.Po # am--include-marker
include lib/liblv/lv_hal/$(DEPDIR)/lv_hal_disp.Po # am--include-marker
include lib/liblv/lv_hal/$(DEPDIR)/lv_hal_indev.Po # am--include-marker
include lib/liblv/lv_hal/$(DEPDIR)/lv_hal_tick.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_anim.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_area.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_async.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_bidi.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_circ.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_color.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_fs.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_gc.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_ll.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_log.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_math.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_mem.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_printf.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_task.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_txt.Po # am--include-marker
include lib/liblv/lv_misc/$(DEPDIR)/lv_utils.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_arc.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_bar.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_btn.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_btnm.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_calendar.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_canvas.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_cb.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_chart.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_cont.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_cpicker.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_ddlist.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_gauge.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_img.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_imgbtn.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_kb.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_label.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_led.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_line.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_list.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_lmeter.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_mbox.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_page.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_preload.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_roller.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_slider.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_spinbox.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_sw.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_ta.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_table.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_tabview.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_tileview.Po # am--include-marker
include lib/liblv/lv_objx/$(DEPDIR)/lv_win.Po # am--include-marker
include lib/liblv/lv_themes/$(DEPDIR)/lv_theme.Po # am--include-marker
include lib/liblv/lv_themes/$(DEPDIR)/lv_theme_alien.Po # am--include-marker
include lib/liblv/lv_themes/$(DEPDIR)/lv_theme_default.Po # am--include-marker
include lib/liblv/lv_themes/$(DEPDIR)/lv_theme_material.Po # am--include-marker
include lib/liblv/lv_themes/$(DEPDIR)/lv_theme_mono.Po # am--include-marker
include lib/liblv/lv_themes/$(DEPDIR)/lv_theme_nemo.Po # am--include-marker
include lib/liblv/lv_themes/$(DEPDIR)/lv_theme_night.Po # am--include-marker
include lib/liblv/lv_themes/$(DEPDIR)/lv_theme_templ.Po # am--include-marker
include lib/liblv/lv_themes/$(DEPDIR)/lv_theme_zen.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-zstd: distdir
	tardir=$(distdir) && $(am__tar) | zstd -c $${ZSTD_CLEVEL-$${ZSTD_OPT--19}} >$(distdir).tar.zst
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	*.tar.zst*) \
	  zstd -dc $(distdir).tar.zst | $(am__untar) ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f backends/$(DEPDIR)/$(am__dirstamp)
	-rm -f backends/$(am__dirstamp)
	-rm -f lib/liblv/lv_core/$(DEPDIR)/$(am__dirstamp)
	-rm -f lib/liblv/lv_core/$(am__dirstamp)
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/$(am__dirstamp)
	-rm -f lib/liblv/lv_draw/$(am__dirstamp)
	-rm -f lib/liblv/lv_font/$(DEPDIR)/$(am__dirstamp)
	-rm -f lib/liblv/lv_font/$(am__dirstamp)
	-rm -f lib/liblv/lv_hal/$(DEPDIR)/$(am__dirstamp)
	-rm -f lib/liblv/lv_hal/$(am__dirstamp)
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/$(am__dirstamp)
	-rm -f lib/liblv/lv_misc/$(am__dirstamp)
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/$(am__dirstamp)
	-rm -f lib/liblv/lv_objx/$(am__dirstamp)
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/$(am__dirstamp)
	-rm -f lib/liblv/lv_themes/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f ./$(DEPDIR)/antfx.Po
	-rm -f ./$(DEPDIR)/antfxapp.Po
	-rm -f backends/$(DEPDIR)/fb_engine.Po
	-rm -f backends/$(DEPDIR)/sdl2_engine.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_debug.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_disp.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_group.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_indev.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_obj.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_refr.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_style.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_arc.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_basic.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_img.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_label.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_line.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_rect.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_triangle.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_img_cache.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_img_decoder.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_fmt_txt.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_12.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_16.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_22.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_28.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_unscii_8.Po
	-rm -f lib/liblv/lv_hal/$(DEPDIR)/lv_hal_disp.Po
	-rm -f lib/liblv/lv_hal/$(DEPDIR)/lv_hal_indev.Po
	-rm -f lib/liblv/lv_hal/$(DEPDIR)/lv_hal_tick.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_anim.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_area.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_async.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_bidi.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_circ.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_color.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_fs.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_gc.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_ll.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_log.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_math.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_mem.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_printf.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_task.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_txt.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_utils.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_arc.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_bar.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_btn.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_btnm.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_calendar.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_canvas.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_cb.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_chart.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_cont.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_cpicker.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_ddlist.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_gauge.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_img.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_imgbtn.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_kb.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_label.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_led.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_line.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_list.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_lmeter.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_mbox.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_page.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_preload.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_roller.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_slider.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_spinbox.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_sw.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_ta.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_table.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_tabview.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_tileview.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_win.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_alien.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_default.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_material.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_mono.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_nemo.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_night.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_templ.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_zen.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f ./$(DEPDIR)/antfx.Po
	-rm -f ./$(DEPDIR)/antfxapp.Po
	-rm -f backends/$(DEPDIR)/fb_engine.Po
	-rm -f backends/$(DEPDIR)/sdl2_engine.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_debug.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_disp.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_group.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_indev.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_obj.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_refr.Po
	-rm -f lib/liblv/lv_core/$(DEPDIR)/lv_style.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_arc.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_basic.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_img.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_label.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_line.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_rect.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_draw_triangle.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_img_cache.Po
	-rm -f lib/liblv/lv_draw/$(DEPDIR)/lv_img_decoder.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_fmt_txt.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_12.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_16.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_22.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_roboto_28.Po
	-rm -f lib/liblv/lv_font/$(DEPDIR)/lv_font_unscii_8.Po
	-rm -f lib/liblv/lv_hal/$(DEPDIR)/lv_hal_disp.Po
	-rm -f lib/liblv/lv_hal/$(DEPDIR)/lv_hal_indev.Po
	-rm -f lib/liblv/lv_hal/$(DEPDIR)/lv_hal_tick.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_anim.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_area.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_async.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_bidi.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_circ.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_color.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_fs.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_gc.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_ll.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_log.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_math.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_mem.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_printf.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_task.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_txt.Po
	-rm -f lib/liblv/lv_misc/$(DEPDIR)/lv_utils.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_arc.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_bar.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_btn.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_btnm.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_calendar.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_canvas.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_cb.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_chart.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_cont.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_cpicker.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_ddlist.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_gauge.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_img.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_imgbtn.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_kb.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_label.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_led.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_line.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_list.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_lmeter.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_mbox.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_page.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_preload.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_roller.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_slider.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_spinbox.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_sw.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_ta.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_table.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_tabview.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_tileview.Po
	-rm -f lib/liblv/lv_objx/$(DEPDIR)/lv_win.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_alien.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_default.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_material.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_mono.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_nemo.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_night.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_templ.Po
	-rm -f lib/liblv/lv_themes/$(DEPDIR)/lv_theme_zen.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--depfiles am--refresh check \
	check-am clean clean-binPROGRAMS clean-cscope clean-generic \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	dist-zstd distcheck distclean distclean-compile \
	distclean-generic distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
